**1. Self Attention📌**

아래 코드를 수행해보고, Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명: Self Attention은 입력 문장에서 각 단어가 문장 내 다른 단어들과의 관계를 얼마나 중요하게 여겨야 하는지를 학습하는 방법이다.

In [1]:
import numpy as np

# 간단한 문장: ['나는', '사과를', '먹었다']
words = ['나는', '사과를', '먹었다']
word_vectors = {
    '나는': np.array([1, 0, 0]),
    '사과를': np.array([0, 1, 0]), # 각 단어에 대한 임베딩
    '먹었다': np.array([0, 0, 1])
}

# 유사도 계산 함수 (self-attention)
# query와 key 벡터 간의 내적(dot product)을 통해 유사도를 계산
def self_attention(query, key):
    return np.dot(query, key)

attention_matrix = np.zeros((len(words), len(words)))
# 문장 내의 모든 단어 쌍에 대해 self-attention score를 계산
for i in range(len(words)):
    for j in range(len(words)):
      # 각 단어 쌍 (query와 key) 간의 attention score를 계산
        attention_matrix[i][j] = self_attention(word_vectors[words[i]], word_vectors[words[j]])

# 최종 self-attention 행렬 출력
print("Self-Attention Matrix:")
print(attention_matrix)


Self-Attention Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**2. Multi-Head Self Attention📌**

아래 코드를 수행해보고, Multi-Head Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명: Self Attention을 여러 개의 head로 나누어 병렬로 수행하는 방식이다. 각 head는 입력을 다른 방식으로 변환하여 서로 다른 부분의 정보를 학습한다.

In [2]:
# 여러 개의 attention heads
def multi_head_self_attention(query, key, heads=3):
  # query와 key의 내적(dot product)을 여러 번(heads 개수만큼) 계산하여 각 head에 대해 유사도를 구함
    return [np.dot(query, key) for _ in range(heads)] # 각 head에서 동일한 query, key에 대한 attention을 계산


multi_head_attention_matrix = np.zeros((len(words), len(words), 3))
# 문장 내의 모든 단어 쌍에 대해 multi-head self-attention score를 계산
for i in range(len(words)):
    for j in range(len(words)):
        multi_head_attention_matrix[i][j] = multi_head_self_attention(word_vectors[words[i]], word_vectors[words[j]])
# 최종 multi-head self-attention 행렬 출력
print("\nMulti-Head Self-Attention Matrix:")
print(multi_head_attention_matrix)



Multi-Head Self-Attention Matrix:
[[[1. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [1. 1. 1.]]]


**3. Masked Multi-Head Self Attention📌**

아래 코드를 수행해보고, Masked Multi-Head Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명: Self Attention에서 일부 단어에 대한 정보를 보지 못하도록 masking을 적용하는 메커니즘이다. 이 방법은 특히 언어 모델에서 미래의 단어를 예측할 때 유용하다.

In [ ]:
# 마스크 추가: 현재 단어 이후의 단어는 계산하지 않음
def masked_attention(query, key, mask):
  # query와 key 간의 내적 계산 후 mask 값을 곱하여 attention 계산
    return np.dot(query, key) * mask

mask = np.array([1, 1, 0])  # 첫 번째, 두 번째는 보지만, 세 번째는 보지 않음 (이 빈칸 꼭 채워주세요 :) )
masked_attention_matrix = np.zeros((len(words), len(words))) # Masked Attention 행렬 생성
for i in range(len(words)): # 문장 내의 모든 단어 쌍에 대해 masked self-attention score를 계산
    for j in range(len(words)):
      # mask[j]를 적용하여 각 단어 쌍의 attention을 계산
        masked_attention_matrix[i][j] = masked_attention(word_vectors[words[i]], word_vectors[words[j]], mask[j])

# 최종 masked self-attention 행렬 출력
print("\nMasked Self-Attention Matrix:")
print(masked_attention_matrix)



Masked Self-Attention Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


**4. Cross Attention📌**

아래 코드를 수행해보고, Cross Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명:

In [ ]:
# 입력 문장과 응답 문장
question_words = ['너는', '사과를'] # 질문 단어들
answer_words = ['나는', '먹었다'] # 응답 단어들
# 각 질문 단어에 대한 벡터
question_vectors = {
    '너는': np.array([1, 0]),
    '사과를': np.array([0, 1])
}
# 각 응답 단어에 대한 벡터
answer_vectors = {
    '나는': np.array([1, 0]),
    '먹었다': np.array([0, 1])
}

# Cross-Attention
cross_attention_matrix = np.zeros((len(question_words), len(answer_words)))
# 질문 단어와 응답 단어 간의 Attention 계산
for i in range(len(question_words)):
    for j in range(len(answer_words)):
        cross_attention_matrix[i][j] = np.dot(question_vectors[question_words[i]], answer_vectors[answer_words[j]]) # 각 질문 단어와 응답 단어의 벡터 간 내적을 계산하여 Attention score를 구함
# 최종 Cross-Attention 행렬 출력
print("\nCross-Attention Matrix:")
print(cross_attention_matrix)


Cross-Attention Matrix:
[[1. 0.]
 [0. 1.]]
