**1. Self Attention📌**

아래 코드를 수행해보고, Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명: 단어 하나가 query가 되고 나머지가 key가 되어, query와 각 key 사이의 연관성을 내적을 통해 계산한다.

In [1]:
import numpy as np

# 간단한 문장: ['나는', '사과를', '먹었다']
words = ['나는', '사과를', '먹었다']
word_vectors = {
    '나는': np.array([1, 0, 0]),
    '사과를': np.array([0, 1, 0]),
    '먹었다': np.array([0, 0, 1])
}

# 유사도 계산 함수 (self-attention)
def self_attention(query, key):
    return np.dot(query, key) # 벡터 내적으로 연관성 계산

attention_matrix = np.zeros((len(words), len(words)))
for i in range(len(words)):      # 모든 단어가 한번씩 query가 됨
    for j in range(len(words)):  # 각 단어들이 key가 되어
        attention_matrix[i][j] = self_attention(word_vectors[words[i]], word_vectors[words[j]]) # 연관성 계산 후 해당하는 행렬 위치에 추가

print("Self-Attention Matrix:")
print(attention_matrix)


Self-Attention Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**2. Multi-Head Self Attention📌**

아래 코드를 수행해보고, Multi-Head Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명: attention을 head의 개수 만큼 나누어 병렬적으로 수행

In [2]:
# 여러 개의 attention heads
def multi_head_self_attention(query, key, heads=3):
    return [np.dot(query, key) for _ in range(heads)]  # 연관성 계산 시 head 수 만큼 계산

multi_head_attention_matrix = np.zeros((len(words), len(words), 3)) # head 수 만큼
for i in range(len(words)):      # 모든 단어가 한번씩 query가 됨
    for j in range(len(words)):  # 각 단어들이 key가 되어
        multi_head_attention_matrix[i][j] = multi_head_self_attention(word_vectors[words[i]], word_vectors[words[j]])
        # self attention 적용. head 수 만큼 단어의 관계를 다각적으로 분석

print("\nMulti-Head Self-Attention Matrix:")
print(multi_head_attention_matrix)



Multi-Head Self-Attention Matrix:
[[[1. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [1. 1. 1.]]]


**3. Masked Multi-Head Self Attention📌**

아래 코드를 수행해보고, Masked Multi-Head Self Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명:마스크를 사용하여 특정 단어들의 연관성 분석 제한. 주로 미래 단어들을 참조하지 못하게 차단하는데 사용

In [3]:
# 마스크 추가: 현재 단어 이후의 단어는 계산하지 않음
def masked_attention(query, key, mask):
    return np.dot(query, key) * mask   # mask 값이 0이면 해당 attetion 값은 계산하지 않음

mask = np.array([1, 1, 0])  # 첫 번째, 두 번째는 보지만, 세 번째는 masking (이 빈칸 꼭 채워주세요 :) )
masked_attention_matrix = np.zeros((len(words), len(words)))
for i in range(len(words)):
    for j in range(len(words)):
        masked_attention_matrix[i][j] = masked_attention(word_vectors[words[i]], word_vectors[words[j]], mask[j])

print("\nMasked Self-Attention Matrix:")
print(masked_attention_matrix)



Masked Self-Attention Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


**4. Cross Attention📌**

아래 코드를 수행해보고, Cross Attention은 어떤 메커니즘인지 설명하고,

 그 설명에 맞게 각 코드에 직접 주석을 달아봅시다.

 ✅설명:질문과 응답 문장 간의 attention 계산

In [4]:
# 입력 문장과 응답 문장
question_words = ['너는', '사과를']
answer_words = ['나는', '먹었다']
question_vectors = {
    '너는': np.array([1, 0]),
    '사과를': np.array([0, 1])
}
answer_vectors = {
    '나는': np.array([1, 0]),
    '먹었다': np.array([0, 1])
}

# Cross-Attention
cross_attention_matrix = np.zeros((len(question_words), len(answer_words)))
for i in range(len(question_words)):    # 질문 문장의 단어가 query가 되고
    for j in range(len(answer_words)):  # 응답 문장의 단어가 key가 되어
        cross_attention_matrix[i][j] = np.dot(question_vectors[question_words[i]], answer_vectors[answer_words[j]])
        # query와 key의 attention 계산
print("\nCross-Attention Matrix:")
print(cross_attention_matrix)


Cross-Attention Matrix:
[[1. 0.]
 [0. 1.]]
